MVCtemplate1/Controllers/Mahasiswa2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCtemplate1.Entities;
using PagedList;
using System.IO;
using System.Text;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace MVCtemplate1.Controllers
{
    public class Mahasiswa2Controller : Controller
    {
        private SimEntities db = new SimEntities();

        // GET: Mahasiswa2
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var mahasiswa = from s in db.Mahasiswa
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                mahasiswa = mahasiswa.Where(s => s.nama.Contains(searchString)
                                       || s.alamat.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    mahasiswa = mahasiswa.OrderByDescending(s => s.nama);
                    break;
                case "Date":
                    mahasiswa = mahasiswa.OrderBy(s => s.tanggalLahir);
                    break;
                case "date_desc":
                    mahasiswa = mahasiswa.OrderByDescending(s => s.tanggalLahir);
                    break;
                default:
                    mahasiswa = mahasiswa.OrderBy(s => s.nama);
                    break;
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return View(mahasiswa.ToPagedList(pageNumber, pageSize));
        }

        // GET: Mahasiswa2/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mahasiswa mahasiswa = db.Mahasiswa.Find(id);
            if (mahasiswa == null)
            {
                return HttpNotFound();
            }
            return View(mahasiswa);
        }

        // GET: Mahasiswa2/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mahasiswa2/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nim,nama,tanggalLahir,jenisKelamin,alamat")] Mahasiswa mahasiswa)
        {
            if (ModelState.IsValid)
            {
                db.Mahasiswa.Add(mahasiswa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mahasiswa);
        }

        // GET: Mahasiswa2/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mahasiswa mahasiswa = db.Mahasiswa.Find(id);
            if (mahasiswa == null)
            {
                return HttpNotFound();
            }
            return View(mahasiswa);
        }

        // POST: Mahasiswa2/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nim,nama,tanggalLahir,jenisKelamin,alamat")] Mahasiswa mahasiswa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mahasiswa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mahasiswa);
        }

        // GET: Mahasiswa2/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mahasiswa mahasiswa = db.Mahasiswa.Find(id);
            if (mahasiswa == null)
            {
                return HttpNotFound();
            }
            return View(mahasiswa);
        }

        // POST: Mahasiswa2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Mahasiswa mahasiswa = db.Mahasiswa.Find(id);
            db.Mahasiswa.Remove(mahasiswa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public FileResult CreatePdf()
        {
            MemoryStream workStream = new MemoryStream();
            StringBuilder status = new StringBuilder("");
            DateTime dTime = DateTime.Now;
            //file name to be created   
            string strPDFFileName = string.Format("SamplePdf" + dTime.ToString("yyyyMMdd") + "-" + ".pdf");
            Document doc = new Document();
            doc.SetMargins(0f, 0f, 0f, 0f);
            //Create PDF Table with 5 columns  
            PdfPTable tableLayout = new PdfPTable(5);
            doc.SetMargins(0f, 0f, 0f, 0f);
            //Create PDF Table  

            //file will created in this path  
            string strAttachment = Server.MapPath("~/Downloads/" + strPDFFileName);


            PdfWriter.GetInstance(doc, workStream).CloseStream = false;
            doc.Open();

            //Add Content to PDF   
            doc.Add(Add_Content_To_PDF(tableLayout));

            // Closing the document  
            doc.Close();

            byte[] byteInfo = workStream.ToArray();
            workStream.Write(byteInfo, 0, byteInfo.Length);
            workStream.Position = 0;


            return File(workStream, "application/pdf", strPDFFileName);

        }

        #region HELPER
        protected PdfPTable Add_Content_To_PDF(PdfPTable tableLayout)
        {

            float[] headers = { 50, 24, 45, 35, 50 }; //Header Widths  
            tableLayout.SetWidths(headers); //Set the pdf headers  
            tableLayout.WidthPercentage = 100; //Set the PDF File witdh percentage  
            tableLayout.HeaderRows = 1;
            //Add Title to the PDF file at the top  

            List<Mahasiswa> employees = db.Mahasiswa.ToList<Mahasiswa>();

            tableLayout.AddCell(new PdfPCell(new Phrase("Creating Pdf using ItextSharp", new Font(Font.FontFamily.HELVETICA, 8, 1, new iTextSharp.text.BaseColor(0, 0, 0)))) {
                Colspan = 12, Border = 0, PaddingBottom = 5, HorizontalAlignment = Element.ALIGN_CENTER
            });

            ////Add header  
            AddCellToHeader(tableLayout, "NIM");
            AddCellToHeader(tableLayout, "Nama");
            AddCellToHeader(tableLayout, "Tanggal Lahir");
            AddCellToHeader(tableLayout, "Jenis Kelamin");
            AddCellToHeader(tableLayout, "alamat");

            ////Add body  
            foreach (var emp in employees)
            {

                AddCellToBody(tableLayout, emp.nim);
                AddCellToBody(tableLayout, emp.nama);
                AddCellToBody(tableLayout, emp.tanggalLahir.ToString());
                AddCellToBody(tableLayout, emp.jenisKelamin);
                AddCellToBody(tableLayout, emp.alamat);

            }

            return tableLayout;
        }
        // Method to add single cell to the Header  
        private static void AddCellToHeader(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.YELLOW)))
            {
                HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(128, 0, 0)
            });
        }
        // Method to add single cell to the body  
        private static void AddCellToBody(PdfPTable tableLayout, string cellText)
        {
            tableLayout.AddCell(new PdfPCell(new Phrase(cellText, new Font(Font.FontFamily.HELVETICA, 8, 1, iTextSharp.text.BaseColor.BLACK)))
             {
                HorizontalAlignment = Element.ALIGN_LEFT, Padding = 5, BackgroundColor = new iTextSharp.text.BaseColor(255, 255, 255)
            });
        }
        #endregion HELPER
    }
}

MVCtemplate1/Views/Mahasiswa2/Create.cshtml
@model MVCtemplate1.Entities.Mahasiswa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mahasiswa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tanggalLahir, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tanggalLahir, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tanggalLahir, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jenisKelamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jenisKelamin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jenisKelamin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alamat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alamat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCtemplate1/Views/Mahasiswa2/Delete.cshtml
@model MVCtemplate1.Entities.Mahasiswa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mahasiswa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tanggalLahir)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tanggalLahir)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jenisKelamin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jenisKelamin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alamat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alamat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCtemplate1/Views/Mahasiswa2/Details.cshtml
@model MVCtemplate1.Entities.Mahasiswa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Mahasiswa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tanggalLahir)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tanggalLahir)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jenisKelamin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jenisKelamin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.alamat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.alamat)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.nim }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCtemplate1/Views/Mahasiswa2/Edit.cshtml
@model MVCtemplate1.Entities.Mahasiswa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mahasiswa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.nim)

        <div class="form-group">
            @Html.LabelFor(model => model.nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tanggalLahir, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tanggalLahir, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tanggalLahir, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jenisKelamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jenisKelamin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jenisKelamin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.alamat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.alamat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCtemplate1/Views/Mahasiswa2/Index.cshtml
@model PagedList.IPagedList<MVCtemplate1.Entities.Mahasiswa>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "Mahasiswa2", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @Html.ActionLink("Tanggal Lahir", "Index", new { sortOrder = ViewBag.DateSortParm })
        </th>
        <th>
            Jenis Kelamin
        </th>
        <th>
            Alamat
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tanggalLahir)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.jenisKelamin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.alamat)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.nim }) |
            @Html.ActionLink("Details", "Details", new { id=item.nim }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.nim })
        </td>
    </tr>
}

</table>

<div class = "col-sm-2">
    <div class = "btnbtn-success" > @Html.ActionLink("Create Pdf", "CreatePdf", "Mahasiswa2")</div>
</div>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))